print("Welcome to the tip calculator! ")
Bill = input("What was the total bill? ")
tip_amount = input("How much tip would you like to give? 10, 12, or 15? ")
people_amount = input("How many people to split the bill? ")
print(f"Each person should pay: {((int(Bill) * int(tip_amount)/100 +int(Bill))/int(people_amount))}")